# Generated by Django 5.0.2 on 2024-03-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0002_alter_user_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='order_number',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
    ]
